Repository Yanis-Kouidri/pixel-adventurer, pull requests merged in 2023-06, with the labels that each got.

#11 Feature/map Tests v0.1
  test/gameengine/map/model/MapArrayClassTest.java
  test/gameengine/map/model/MapClassTest.java
  test/gameengine/map/model/MapTypeClassTest.java
  test/gameengine/map/model/TileClassTest.java
  test/gameengine/map/view/TilesetClassTest.java
Labels: enhancement

#14 Feature/Window Réorganisation du package application pour respecter l…
  src/gameengine/application/view/ApplicationWindow.java
  src/gameengine/application/view/CustomPanel.java
  src/gameengine/application/view/GamePanel.java
  src/gameengine/application/view/MenuPanel.java
  src/gameengine/application/view/PanelMediator.java
Labels: invalid

#13 Feature/Map Classe MapPanel.java v0.1 Ajout de la classe de vue MapPa…
  src/gameassets/map/images/testBackground.png
  src/gameengine/map/view/MapPanel.java
Labels: enhancement

#15 Feature/inventory
  .gitignore
  src/gameengine/inventory/controller/InventoryKeyController.java
  src/gameengine/inventory/model/Inventory.java
  src/gameengine/inventory/model/InventoryFullException.java
  src/gameengine/inventory/model/Item.java
  src/gameengine/inventory/model/NotEmptyPlaceException.java
  src/gameengine/inventory/model/NothingToRemoveException.java
  src/gameengine/inventory/view/InventoryBar.java
  src/gameengine/inventory/view/InventoryMenu.java
  src/gameengine/inventory/view/InventoryPanel.java
  test/gameassets/item/crab.png
  test/gameassets/item/fishing-rod.png
  test/gameassets/item/lemon.png
  test/gameassets/item/potions.png
  test/gameassets/item/trout.png
  test/gameengine/inventory/model/InventoryTest.java
  test/gameengine/inventory/model/ItemTest.java
  test/gameengine/inventory/view/InventoryBarViewTest.java
  test/gameengine/inventory/view/InventoryMenuViewTest.java
  uml/Inventory.puml
Labels: enhancement

#16 Feature/Window Modification du fichier Main.java pour respecter le mo…
  src/main/Main.java
Labels: invalid

#24 Feature/mode controle camera
  src/gameengine/application/controller/CameraController.java
  src/gameengine/application/model/Camera.java
  src/gameengine/application/view/GameLayerPanel.java
  src/gameengine/characters/model/Entity.java
  src/gameengine/map/view/MapPanel.java
  src/main/Main.java
Labels: enhancement

#26 Ts/25 ts optimisation du rendu graphique de la map
  src/gameengine/application/view/GameLayerPanel.java
  src/gameengine/map/view/MapPanel.java
  src/gameengine/map/view/Tileset.java
  src/gameengine/utils/model/Constants.java
Labels: enhancement

#29 fixed usage of tile in model instead of pixels
  src/gameengine/application/model/Camera.java
  src/gameengine/application/view/GameLayerPanel.java
  src/gameengine/characters/model/Entity.java
  src/gameengine/characters/view/EntityView.java
  src/gameengine/utils/model/Physics.java
  src/gameengine/utils/model/Utils.java
Labels: enhancement

#33 blocks the camera if it goes outside the map edges
  src/gameengine/application/model/Camera.java
Labels: enhancement

#42 Correction/update uml
  src/gameengine/inventory/model/Inventory.java
  src/gameengine/inventory/model/Item.java
  src/gameengine/inventory/view/ItemsView.java
  test/gameengine/inventory/model/InventoryTest.java
  test/gameengine/inventory/view/InventoryObserverTest.java
  uml/Inventory/InventoryModel.puml
  uml/Inventory/InventoryView.puml
Labels: documentation

#43 Adding icon image to inventory and few corrections
  src/gameengine/inventory/controller/InventoryKeyController.java
  src/gameengine/inventory/controller/InventoryMouseController.java
  src/gameengine/inventory/view/InventoryPanel.java
  src/main/Main.java
Labels: bug, enhancement

#45 41 remove deprecated usage
  src/gameengine/application/controller/CameraController.java
  src/gameengine/application/model/Camera.java
  src/gameengine/application/view/CustomPanel.java
  src/gameengine/application/view/GameLayerPanel.java
  src/gameengine/application/view/MenuPanel.java
  src/main/Main.java
Labels: Cleaning

#46 Adding livrables
  livrables/presentation.pdf
  livrables/rapport.pdf
  livrables/utilisateur.pdf
Labels: documentation
